### ISSUE TITLE
Freeform windows do not work when using SmartDock bar and menu to open apps

### ISSUE THREAD

**Issue by unixman0x6576676C313531303933** [axel358/smartdock#104]
Hello! Wanted to say I love the idea. Android really needs a open source Dex alternative and this is the most promising project out there.

I am running stock Android 12 Snow Cone API Level 31 on a Unihertz Tank 01, the device is rooted, the OS is pretty much vanilla Android as far as I can say, generic chinese build. Sadly SmartDock works only partially for me, tried the 1.11.0 version and 1.9.8. Allowed everything I could, accessibility, drawing on other apps, file access, location, did the pm write secure settings thing, set SmartDock as a device administrator app and the main home screen app. Have all the options for enabling freeform windows and desktop mode checked in the Developer options menu, but I can only launch apps in fullscreen mode from the SmartDock bar and menu, all the other "Open in" options result in launching a blank activity that immediately disappears from the screen. I can still see it in the Recent Apps menu, but it won't launch again normally untill you close it and reopen again.

P.S. - Stock freeform windows work for me when I open them from the Recent App menu, but they do not work when I try to launch apps in freeform mode from the SmartDock itself

Any help would be much appreciated, I can also send you the logs if you tell me were to search. Thank you !

![Screenshot_20231024-150842](https://github.com/axel358/smartdock/assets/80970471/ffc2bd4c-a375-4e1b-b98e-7ae51b8dc0f0)
![Screenshot_20231024-153828](https://github.com/axel358/smartdock/assets/80970471/d4f9bad2-d72d-4165-bfc6-db5f415bf65a)

**Comment by unixman0x6576676C313531303933** [comment]
This is what logcat gave me.

First launched the calculator app fullscreen from the SmartDock menu, witch it did, then closed it and attempted to launch the same app using "Open in Standart" view.

> 10-26 20:44:00.062  1617  3540 I SurfaceFlinger: [SF client] NEW(0xb40000734a148490) for (20986:cu.axel.smartdock)
10-26 20:44:00.065  2458 15102 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:00.068  2458 15102 W WindowManager: Changing focus from Window{ebfb313 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher} to Window{1718516 u0 cu.axel.smartdock} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:465 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:5755 com.android.server.wm.WindowManagerService.addWindow:1856 com.android.server.wm.Session.addToDisplayAsUser:204
10-26 20:44:00.287  3772  3772 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=cu.axel.smartdock, inputType=1, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=8000002, privateImeOptions=null, actionName=GO, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=2131296565, fieldName=null, extras=null, hintText=non-empty, hintLocales=[]}}, false)
10-26 20:44:01.788  1617  2631 I SurfaceFlinger: [SF client] NEW(0xb40000734a142290) for (20986:cu.axel.smartdock)
10-26 20:44:01.791  2458 15102 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:04.274  3772  3772 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=cu.axel.smartdock, inputType=1, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=8000002, privateImeOptions=null, actionName=GO, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=2131296565, fieldName=null, extras=null, hintText=non-empty, hintLocales=[]}}, true)
10-26 20:44:04.354  3772  3772 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=cu.axel.smartdock, inputType=1, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=2, privateImeOptions=null, actionName=GO, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=2131296565, fieldName=null, extras=null, hintText=non-empty, hintLocales=[]}}, false)
10-26 20:44:04.374  2458  8264 W InputManager-JNI: Input channel object 'cbd5dfa cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:04.374  2458  8264 D WindowManager: setParent old=WindowToken{cca3cd1 android.os.Binder@f1e7ff8},new=null,this window=Window{cbd5dfa u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowManagerService.removeWindow:2053
10-26 20:44:04.385  2458  8264 W InputManager-JNI: Input channel object '1718516 cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:04.385  2458  8264 D WindowManager: setParent old=WindowToken{cca3cd1 android.os.Binder@f1e7ff8},new=null,this window=Window{1718516 u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowManagerService.removeWindow:2053
10-26 20:44:04.395  2458  8264 W WindowManager: Changing focus from Window{1718516 u0 cu.axel.smartdock} to Window{f3eae4e u0 com.tricolorcat.calculator/com.tricolorcat.calculator.MainActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:465 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:5755 com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace:815 com.android.server.wm.RootWindowContainer.performSurfacePlacement:797
10-26 20:44:10.722 20986 20986 E ActivityThread: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver cu.axel.smartdock.services.DockService$5@384294e that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.722 20986 20986 E ActivityThread: android.app.IntentReceiverLeaked: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver cu.axel.smartdock.services.DockService$5@384294e that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.722 20986 20986 E ActivityThread:        at cu.axel.smartdock.services.DockService.onServiceConnected(DockService.java:480)
10-26 20:44:10.723 20986 20986 E ActivityThread: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver android.widget.TextClock$1@b781426 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.723 20986 20986 E ActivityThread: android.app.IntentReceiverLeaked: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver android.widget.TextClock$1@b781426 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.724  2458  2458 W InputManager-JNI: Input channel object 'd96b509 cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:10.724  2458  2458 D WindowManager: setParent old=WindowToken{cca3cd1 android.os.Binder@f1e7ff8},new=null,this window=Window{d96b509 u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowToken.removeAllWindowsIfPossible:231
10-26 20:44:10.724 20986 20986 E ActivityThread: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver cu.axel.smartdock.services.DockService$6@ce0a405 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.724 20986 20986 E ActivityThread: android.app.IntentReceiverLeaked: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver cu.axel.smartdock.services.DockService$6@ce0a405 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.724 20986 20986 E ActivityThread:        at cu.axel.smartdock.services.DockService.onServiceConnected(DockService.java:507)
10-26 20:44:10.726 20986 20986 E ActivityThread: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver cu.axel.smartdock.services.DockService$3@ee48c49 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.726 20986 20986 E ActivityThread: android.app.IntentReceiverLeaked: Service cu.axel.smartdock.services.DockService has leaked IntentReceiver cu.axel.smartdock.services.DockService$3@ee48c49 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-26 20:44:10.726 20986 20986 E ActivityThread:        at cu.axel.smartdock.services.DockService.onServiceConnected(DockService.java:461)
10-26 20:44:10.726  2458  2458 W InputManager-JNI: Input channel object '566dcc2 cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:10.727  2458  2458 D WindowManager: setParent old=WindowToken{cca3cd1 android.os.Binder@f1e7ff8},new=null,this window=Window{566dcc2 u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowToken.removeAllWindowsIfPossible:231
10-26 20:44:10.729  2458  2458 W InputManager-JNI: Input channel object '9a6c237 cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:10.729  2458  2458 D WindowManager: setParent old=WindowToken{cca3cd1 android.os.Binder@f1e7ff8},new=null,this window=Window{9a6c237 u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowToken.removeAllWindowsIfPossible:231
10-26 20:44:11.535  1617  2631 I SurfaceFlinger: [SF client] NEW(0xb40000734a138510) for (20986:cu.axel.smartdock)
10-26 20:44:11.538  2458 13510 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:11.546  1617  2631 I SurfaceFlinger: [SF client] NEW(0xb40000734a13e390) for (20986:cu.axel.smartdock)
10-26 20:44:11.550  2458 13510 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:11.557  1617  2631 I SurfaceFlinger: [SF client] NEW(0xb40000734a141ff0) for (20986:cu.axel.smartdock)
10-26 20:44:11.561  2458 13510 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:11.866  2863  2863 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|android|0|com.android.server.wm.AlertWindowNotification - cu.axel.smartdock|1000
10-26 20:44:11.866  2863  2863 D InterruptionStateProvider: No heads up: unimportant notification: 0|android|0|com.android.server.wm.AlertWindowNotification - cu.axel.smartdock|1000
10-26 20:44:12.637  1617  2631 I SurfaceFlinger: [SF client] NEW(0xb40000734a14b670) for (20986:cu.axel.smartdock)
10-26 20:44:12.640  2458  3204 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:12.641  2458  3204 W WindowManager: Changing focus from Window{ebfb313 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher} to Window{474f89c u0 cu.axel.smartdock} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:465 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:5755 com.android.server.wm.WindowManagerService.addWindow:1856 com.android.server.wm.Session.addToDisplayAsUser:204
10-26 20:44:12.897  3772  3772 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=cu.axel.smartdock, inputType=1, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=8000002, privateImeOptions=null, actionName=GO, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=2131296565, fieldName=null, extras=null, hintText=non-empty, hintLocales=[]}}, false)
10-26 20:44:13.353 30152 30152 E u4java_WebContentsAccessibilityImpl: [InfoLevelMessage] system accessibility service is enabled: cu.axel.smartdock/.services.DockService
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.472  2458  2804 D CtrlChargingForAging: <aguiGetCurrentFocusWindow> result=cu.axel.smartdock
10-26 20:44:14.771  1617  2631 I SurfaceFlinger: [SF client] NEW(0xb40000734a14b3d0) for (20986:cu.axel.smartdock)
10-26 20:44:14.774  2458 15102 W AppOps  : Noting op not finished: uid 10277 pkg cu.axel.smartdock code 24 startTime of in progress event=1698342084575
10-26 20:44:15.744  2458  5739 V SettingsProvider: packageValueForCallResult, name = enabled_accessibility_services, value : Bundle[{_track_generation=android.util.MemoryIntArray@ae, value=com.cannic.apps.rlbubble/.services.BubbleService:cu.axel.smartdock/.services.DockService, _generation_index=2, _generation=34}]
10-26 20:44:16.174  2458  5739 V SettingsProvider: packageValueForCallResult, name = enabled_accessibility_services, value : Bundle[{_track_generation=android.util.MemoryIntArray@ae, value=com.cannic.apps.rlbubble/.services.BubbleService:cu.axel.smartdock/.services.DockService, _generation_index=2, _generation=34}]
10-26 20:44:18.166  3772  3772 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=cu.axel.smartdock, inputType=1, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=8000002, privateImeOptions=null, actionName=GO, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=2131296565, fieldName=null, extras=null, hintText=non-empty, hintLocales=[]}}, true)
10-26 20:44:18.222  3772  3772 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1894 onStartInput(EditorInfo{EditorInfo{packageName=cu.axel.smartdock, inputType=1, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=2, privateImeOptions=null, actionName=GO, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=2131296565, fieldName=null, extras=null, hintText=non-empty, hintLocales=[]}}, false)
10-26 20:44:18.235  2458  5739 W InputManager-JNI: Input channel object '9393b33 cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:18.236  2458  5739 D WindowManager: setParent old=WindowToken{a501438 android.os.Binder@d17089b},new=null,this window=Window{9393b33 u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowManagerService.removeWindow:2053
10-26 20:44:18.241  2458  5739 W InputManager-JNI: Input channel object '474f89c cu.axel.smartdock (client)' was disposed without first being removed with the input manager!
10-26 20:44:18.242  2458  5739 D WindowManager: setParent old=WindowToken{a501438 android.os.Binder@d17089b},new=null,this window=Window{474f89c u0 cu.axel.smartdock},callers=com.android.server.wm.WindowContainer.removeChild:594 com.android.server.wm.WindowContainer.removeImmediately:646 com.android.server.wm.WindowState.removeImmediately:2380 com.android.server.wm.WindowState.removeIfPossible:2567 com.android.server.wm.WindowState.removeIfPossible:2437 com.android.server.wm.WindowManagerService.removeWindow:2053
10-26 20:44:18.245  2458  5739 W WindowManager: Changing focus from Window{474f89c u0 cu.axel.smartdock} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:465 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:5755 com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace:815 com.android.server.wm.RootWindowContainer.performSurfacePlacement:797
